language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/parallel-lint Nella
